# Generated by Django 5.2.1 on 2025-06-11 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('cognoms', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('tipus', models.CharField(choices=[('ADM', 'Administrador'), ('RES', 'Responsable Borsa'), ('EST', 'Estudiant'), ('EMP', 'Empresa')], default='EST', max_length=3)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('adreca', models.TextField(blank=True, null=True)),
                ('data_registre', models.DateTimeField(auto_now_add=True)),
                ('darrera_connexio', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapacitatClau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('descripcio', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Capacitat Clau',
                'verbose_name_plural': 'Capacitats Clau',
            },
        ),
        migrations.CreateModel(
            name='FamiliaProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=5, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Famílies Professionals',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField()),
                ('cos', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='noticies/imatges/')),
                ('document', models.FileField(blank=True, null=True, upload_to='noticies/documents/')),
                ('destinatari', models.CharField(choices=[('TOTHOM', 'Tothom'), ('ESTUDIANTS', 'Estudiants'), ('EMPRESES', 'Empreses')], default='TOTHOM', max_length=10)),
                ('data_publicacio', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícies',
                'ordering': ['-data_publicacio'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('nom_comercial', models.CharField(max_length=150)),
                ('rao_social', models.CharField(max_length=150)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('num_treballadors', models.IntegerField(blank=True, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('email_contacte', models.EmailField(blank=True, max_length=254, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borsa_treball.sector')),
            ],
            options={
                'verbose_name_plural': 'empreses',
            },
        ),
        migrations.CreateModel(
            name='Estudiant',
            fields=[
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=5)),
                ('nom', models.CharField(max_length=150)),
                ('grau', models.CharField(choices=[('GM', 'Grau Mitjà'), ('GS', 'Grau Superior'), ('ESP', 'Especialització')], max_length=3)),
                ('durada', models.IntegerField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borsa_treball.familiaprofessional')),
            ],
            options={
                'unique_together': {('familia', 'codi')},
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('numero_vacants', models.PositiveSmallIntegerField(default=1, verbose_name='Número vacants')),
                ('data_limit', models.DateField()),
                ('lloc_treball', models.CharField(max_length=100)),
                ('tipus_contracte', models.CharField(choices=[('PR', 'Pràctiques'), ('TC', 'Contracte en pràctiques'), ('TI', 'Contracte temporal'), ('IN', 'Contracte indefinit'), ('FP', 'Formació professional dual')], max_length=2)),
                ('jornada', models.CharField(choices=[('CO', 'Completa'), ('PA', 'Parcial'), ('FL', 'Flexible')], max_length=2)),
                ('hores_setmanals', models.PositiveSmallIntegerField(blank=True, help_text="Només s'utilitza si la jornada és parcial", null=True, verbose_name='Hores setmanals')),
                ('horari', models.CharField(blank=True, max_length=100, null=True)),
                ('public_destinatari', models.CharField(blank=True, choices=[('EST', 'Estudiant'), ('TIT', 'Titulat/da'), ('AMB', 'Estudiant i Titulat/da')], default='AMB', max_length=3, null=True, verbose_name='A qui va dirigida')),
                ('experiencia', models.CharField(blank=True, choices=[('SE', 'Sense experiència'), ('2A', '> 2 anys'), ('5A', '> 5 anys')], max_length=2, null=True, verbose_name='Experiència requerida')),
                ('salari', models.CharField(blank=True, max_length=50, null=True)),
                ('data_publicacio', models.DateField(auto_now_add=True)),
                ('requisits', models.TextField(blank=True, null=True)),
                ('contacte_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('contacte_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacte_telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('visible', models.BooleanField(default=True, help_text="Controlat per l'empresa")),
                ('activa', models.BooleanField(default=False, help_text='Activat pel responsable de la borsa de treball')),
                ('tancada', models.BooleanField(default=False, help_text="Indica si l'oferta ha estat tancada (ja s'ha cobert la vacant, etc.)", verbose_name='Oferta tancada')),
                ('valoracio_empresa', models.TextField(blank=True, help_text="La valoració de l'empresa sobre el procés o els candidats.", null=True, verbose_name="Valoració de l'Empresa")),
                ('valoracio_responsable', models.TextField(blank=True, help_text='La valoració del responsable de la borsa de treball sobre el procés.', null=True, verbose_name='Valoració del Responsable')),
                ('capacitats_clau', models.ManyToManyField(blank=True, related_name='ofertes', to='borsa_treball.capacitatclau')),
                ('cicles', models.ManyToManyField(related_name='ofertes', to='borsa_treball.cicle')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertes', to='borsa_treball.empresa')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertes',
                'ordering': ['-data_publicacio'],
            },
        ),
        migrations.CreateModel(
            name='NivellIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(blank=True, help_text='Ex: anglès, català...', max_length=100)),
                ('nivell', models.CharField(blank=True, help_text='Ex: alt, mitjà, nadiu...', max_length=100)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomes', to='borsa_treball.oferta')),
            ],
            options={
                'verbose_name': "Nivell d'idioma",
                'verbose_name_plural': "Nivells d'idioma",
            },
        ),
        migrations.CreateModel(
            name='Funcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcions', to='borsa_treball.oferta')),
            ],
            options={
                'verbose_name': 'Funció',
                'verbose_name_plural': 'Funcions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RegistreAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accio', models.CharField(max_length=50)),
                ('model_afectat', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('revisat', models.BooleanField(default=False)),
                ('usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Registre d'auditoria",
                'verbose_name_plural': "Registres d'auditoria",
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EstudiEstudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_inici', models.IntegerField(help_text='Any en què va començar aquest cicle', verbose_name="Any d'inici")),
                ('any_fi', models.IntegerField(blank=True, help_text='Any en què va finalitzar o preveu finalitzar', null=True, verbose_name='Any de finalització')),
                ('centre_estudis', models.CharField(blank=True, help_text='Nom del centre on es cursa/va cursar', max_length=200, null=True, verbose_name="Centre d'estudis")),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('cicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiants_matriculats', to='borsa_treball.cicle')),
                ('estudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudis', to='borsa_treball.estudiant')),
            ],
            options={
                'verbose_name': 'Estudi estudiant',
                'verbose_name_plural': 'Estudis estudiant',
                'ordering': ['-any_inici'],
                'unique_together': {('estudiant', 'cicle', 'any_inici')},
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True, verbose_name='Data de candidatura')),
                ('estat', models.CharField(choices=[('RJ', 'Rebutjada'), ('EP', 'En procés'), ('PR', 'Preseleccionada'), ('EN', 'Entrevista programada'), ('CO', 'Contractada')], default='EP', max_length=2, verbose_name='Estat')),
                ('carta_presentacio', models.TextField(blank=True, null=True, verbose_name='Carta de presentació')),
                ('cv_adjunt', models.FileField(blank=True, null=True, upload_to='candidatures/cv/', verbose_name='CV adjunt')),
                ('altres_adjunts', models.FileField(blank=True, null=True, upload_to='candidatures/adjunts/', verbose_name='Altres documents')),
                ('data_canvi_estat', models.DateTimeField(auto_now=True, verbose_name="Últim canvi d'estat")),
                ('notes_empresa', models.TextField(blank=True, null=True, verbose_name="Notes internes de l'empresa")),
                ('puntuacio', models.PositiveSmallIntegerField(blank=True, help_text="Puntuació assignada per l'empresa", null=True, verbose_name='Puntuació (0-100)')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='borsa_treball.oferta', verbose_name='Oferta')),
                ('estudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='borsa_treball.estudiant', verbose_name='Estudiant')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-data_candidatura'],
                'unique_together': {('oferta', 'estudiant')},
            },
        ),
    ]
