# Generated by Django 5.2.3 on 2025-06-24 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumpte', models.CharField(max_length=255)),
                ('contingut', models.TextField()),
                ('llegit', models.BooleanField(default=False)),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('destinatari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges_rebuts', to=settings.AUTH_USER_MODEL)),
                ('remitent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges_enviats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
