# Generated by Django 5.2.1 on 2025-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0002_remove_estudiant_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiant',
            name='carnet_conduir',
            field=models.BooleanField(default=False),
        ),
    ]
