# Generated by Django 5.2.3 on 2025-06-26 09:34

import borsa_treball.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0002_missatge'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='estat',
            field=models.CharField(choices=[('OC', 'Ocult'), ('RV', 'En revisió'), ('AC', 'Actiu'), ('TC', 'Tancat')], default='RV', help_text="Controla la visibilitat i disponibilitat de l'oferta", max_length=2, verbose_name="Estat de l'oferta"),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='altres_adjunts',
            field=models.FileField(blank=True, null=True, upload_to='private/candidatures/adjunts/', verbose_name='Altres documents'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cv_adjunt',
            field=models.FileField(blank=True, null=True, upload_to=borsa_treball.models.curriculum_upload_path, verbose_name='CV adjunt'),
        ),
    ]
