# Generated by Django 5.2.3 on 2025-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0003_oferta_estat_alter_candidatura_altres_adjunts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicle',
            name='codi',
            field=models.CharField(max_length=10),
        ),
    ]
