# Generated by Django 5.2.1 on 2025-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0003_estudiant_carnet_conduir'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='activa',
            field=models.BooleanField(default=False, help_text='Activat pel responsable de la borsa de treball'),
        ),
    ]
