# Generated by Django 5.2.1 on 2025-06-24 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0004_candidatura_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tipus_contracte',
            field=models.CharField(choices=[('PR', 'Pràctiques'), ('TC', 'Contracte en pràctiques'), ('TI', 'Contracte temporal'), ('IN', 'Contracte indefinit')], max_length=2),
        ),
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumpte', models.CharField(max_length=255)),
                ('contingut', models.TextField()),
                ('llegit', models.BooleanField(default=False)),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('destinatari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges_rebuts', to=settings.AUTH_USER_MODEL)),
                ('remitent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges_enviats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
