# Generated by Django 5.2.3 on 2025-06-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0004_alter_cicle_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estat',
            field=models.CharField(choices=[('OC', 'Oculta'), ('RV', 'En revisió'), ('AC', 'Activa'), ('TC', 'Tancada')], default='RV', help_text="Controla la visibilitat i disponibilitat de l'oferta", max_length=2, verbose_name="Estat de l'oferta"),
        ),
        migrations.CreateModel(
            name='CapacitatOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la capacitat clau (lliure o suggerida)', max_length=100)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitats', to='borsa_treball.oferta')),
            ],
            options={
                'verbose_name': "Capacitat clau de l'oferta",
                'verbose_name_plural': "Capacitats clau de l'oferta",
            },
        ),
    ]
