# Generated by Django 5.2.3 on 2025-07-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0005_alter_oferta_estat_capacitatoferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='capacitats_clau',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='tancada',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='visible',
        ),
    ]
