# Generated by Django 5.2.3 on 2025-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0006_remove_oferta_activa_remove_oferta_capacitats_clau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='contacte_telefon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='horari',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='salari',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='titol',
            field=models.CharField(max_length=200),
        ),
    ]
