# Generated by Django 5.2.3 on 2025-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0007_alter_oferta_contacte_telefon_alter_oferta_horari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='data_tancament',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capacitatoferta',
            name='nom',
            field=models.CharField(help_text='Nom de la capacitat clau (lliure o suggerida)', max_length=200),
        ),
    ]
