# Generated by Django 5.2.3 on 2025-07-18 13:08

import borsa_treball.models
import borsa_treball.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa_treball', '0008_oferta_data_tancament_alter_capacitatoferta_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='cv_adjunt',
            field=models.FileField(blank=True, null=True, storage=borsa_treball.storages.PrivateMediaStorage(), upload_to=borsa_treball.models.curriculum_upload_path, verbose_name='CV adjunt'),
        ),
    ]
